refactor: move Crowdin synchronization to a new workflow and update main pages workflow to use Docusaurus translations.

diff --git a/.github/workflows/pages-crowdin.yml b/.github/workflows/pages-crowdin.yml
--- a/.github/workflows/pages-crowdin.yml
+++ b/.github/workflows/pages-crowdin.yml
@@ -40,8 +40,21 @@ jobs:
       - name: Install Dependencies
         run: npm install --include=optional --no-audit --no-fund
       
-      - name: Docusaurus Translations
-        run: npm run write-translations
+      - name: Check Crowdin Token
+        env:
+          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
+        run: |
+          if [ -z "$CROWDIN_PERSONAL_TOKEN" ]; then
+            echo "Error: CROWDIN_PERSONAL_TOKEN is empty or missing!"
+            exit 1
+          else
+            echo "Success: CROWDIN_PERSONAL_TOKEN is set."
+          fi
+
+      - name: Crowdin Translations
+        env:
+          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
+        run: npm run crowdin:sync
 
       - name: Build Docusaurus
         run: npm run build
